version: '3.9'

services:
  mongodb:
    image: mongo
    volumes:
      - ./dev/data/db:/data/db
      - ./dev/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: wishlists
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: root
  app:
    depends_on:
      - mongodb
    build: .
    ports:
      - 8080:8080
    environment:
      MONGODB_DATASOURCE_URI: mongodb://mongo:mongo@mongodb:27017/wishlists